routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|---------------------å-----------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function()
{
    return View::make('pages.landing');
});

//Route::resource('downtime', 'DownTimeController');

// Private Pages
//Route::get('users', 'UsersController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/profile', 'ProfileController');
Route::resource('users', 'UsersController');
Route::resource('courses', 'CoursesController');
Route::resource('modules', 'ModulesController');
Route::resource('slides', 'SlidesController');
Route::resource('enrollment', 'EnrollmentController');
//Route::resource('enrollment_status', 'Enrollment_statusController');
//Route::resource('role', 'RoleController');
//Route::resource('permission', 'PermissionController');
//Route::resource('permission_role', 'Permission_roleController');

Route::get('users/dashboard', 'UsersController@dashboard')->name('users.dashboard');;

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    /**
    * @param string|array $roles
    */
    public function authorizeRoles($roles)
    {
        if (is_array($roles)) {
            return $this->hasAnyRole($roles) || 
                    abort(401, 'This action is unauthorized.');
        }
        return $this->hasRole($roles) || 
                abort(401, 'This action is unauthorized.');
    }

    /**
    * Check multiple roles
    * @param array $roles
    */
    public function hasAnyRole($roles)
    {
        return null !== $this->roles()->whereIn('name', $roles)->first();
    }

    /**
    * Check one role
    * @param string $role
    */
    public function hasRole($role)
    {
        return null !== $this->roles()->where('name', $role)->first();
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User as User;
use App\Course as Course;

class UsersController extends Controller{

    /**
     * Middleware to check for Unauthorized users.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

	public function index(Request $request) {

		// User Authentication + Role Authorization, we check to see if the user as the to access this method
		$request->user()->authorizeRoles(['superadmin', 'admin']);

		$users = User::all();
		return view('users.index', array(
			'users' => $users,
		));
	}
	
	public function show() {
		$courses = Course::all();
		return view('users.show', array('courses'=>$courses));
	}	
	
	public function getApproveUser() {
		$users = User::all();
		return view('users.approve-users', array('users'=>$users));
	}

	/**
	* @param string|array $roles
	*/
	public function authorizeRoles($roles)
	{
	if (is_array($roles)) {
		return $this->hasAnyRole($roles) || 
				abort(401, 'This action is unauthorized.');
	}
	return $this->hasRole($roles) || 
			abort(401, 'This action is unauthorized.');
	}
	/**
	* Check multiple roles
	* @param array $roles
	*/
	public function hasAnyRole($roles)
	{
	return null !== $this->roles()->whereIn(‘name’, $roles)->first();
	}
	/**
	* Check one role
	* @param string $role
	*/
	public function hasRole($role)
	{
	return null !== $this->roles()->where(‘name’, $role)->first();
	}

}

resources/views/users/dashboard.blade.php
@extends('layouts.default')
@section('content')

<h1 class="header smaller lighter blue">Courses</h1>

<div class="row">
	<div class="col-md-12">

	@foreach($courses as $course)
		<div class="col-sm-6 col-xs-12">
			<div class="panel panel-default">
				<div class="panel-heading text-right"> 
						{{ $course->hours }} hours
				</div>
	 			 <div class="panel-body">
					<h3> <a href="{{ route('courses.show', $course->id) }}"> <span class="glyphicon glyphicon-education" aria-hidden="true"></span> {{ $course->name }}</a></h3>

					<div class="hr hr-single hr-dotted hr18"></div>

					<a href="{{ route('courses.show', $course->id) }}" class="btn btn-xs btn-primary" >Explore</a>
					<a href="#" class="btn btn-xs btn-primary" data-toggle="popover" data-trigger="hover" data-content="{{ $course->description }}">Description</a>
					
					@if(Auth::user()->hasRole("superadmin"))
					<a href="{{{ route('courses.edit', $course->id) }}}" class="pull-right" >Edit</a>
					@endif
				</div>
			</div>
		</div>
	@endforeach

	</div>
</div>


@stop

@section('scripts')
<script>
$(document).ready(function(){
    $('[data-toggle="popover"]').popover(); 
});
</script>

@stop 

resources/views/users/edit.blade.php
@extends('layouts.default')
@section('content')


<div class="page-header">
<h1>User profile</h1>
</div>

{{ Form::model($user, array('route' => array('users.update', $user->id)), 'POST') }}

@if(Session::has('message'))
	<p class="alert">{{ Session::get('message') }}</p>
@endif

<input type="hidden" name="_method" value="PUT" />

<div class="profile-user-info profile-user-info-striped">
	<div class="profile-info-row">
		<div class="profile-info-name"> {{ Form::label('firstname', 'First name') }} </div>

		<div class="profile-info-value">
			<span class="editable editable-click" id="username"> {{ Form::text('firstname') }}</span>
		</div>
	</div>
	
	<div class="profile-info-row">
		<div class="profile-info-name"> {{ Form::label('lastname', 'Last name') }}</div>

		<div class="profile-info-value">
			<span class="editable editable-click" id="username"> {{ Form::text('lastname') }}</span>
		</div>
	</div>
	
	<div class="profile-info-row">
		<div class="profile-info-name"> {{ Form::label('email', 'Email') }}</div>

		<div class="profile-info-value">
			<span class="editable editable-click" id="username"> {{ Form::text('email') }}</span>
		</div>
	</div>		
	
	<div class="profile-info-row">
		<div class="profile-info-name">Password</div>

		<div class="profile-info-value">
			<a href="/change-password" class="editable editable-click" id="username">Chanage password</a>
		</div>
	</div>	
	
	
	@if($userRole->hasRole("superadmin"))
	<div class="profile-info-row">
		<div class="profile-info-name">{{ Form::label('email', 'Approve User') }}</div>
		<div class="profile-info-value">
			<span class="editable" id="username">{{ Form::checkbox('approval', 1, null, ['id'=>'id-button-borders', 'class' => 'ace ace-switch ace-switch-5']) }}
			<span class="lbl middle"></span>
			</span>
		</div>
	</div>
	@endif
</div>




<br>
<br>
{{ Form::submit('Save', array('class' => 'btn btn-primary')) }}

{{ Form::close() }}

@stop

resources/views/users/index.blade.php
@extends('layouts.default')
@section('content')

<h1 class="header smaller lighter blue">User Status</h1>

<!-- will be used to show any messages -->
@if (Session::has('message'))
	<div class="alert alert-info">{{ Session::get('message') }}</div>
@endif

<div class="row">
	<div class="col-xs-12">
	
		<div class="clearfix">
			<div class="pull-right tableTools-container"></div>
		</div>


		<!-- div.table-responsive -->

		<!-- div.dataTables_borderWrap -->
		<div>
			<table id="dynamic-table" class="table table-striped table-bordered table-hover">
				<thead>
					<tr>
						<th class="text-center">
							<label class="pos-rel">
								<input type="checkbox" class="ace" />
								<span class="lbl"></span>
							</label>
						</th>
						<th>User Name</th>
						<th>Email</th>
						<th class="text-center">Status</th>
						<th class="col-md-2 text-right">Actions</th>
					</tr>
				</thead>

				<tbody>
				
				@foreach($users as $user)
					<tr>
						<td class="text-center">
							<label class="pos-rel">
								<input type="checkbox" class="ace" />
								<span class="lbl"></span>
							</label>
						</td>

						<td>
							<a href="/users/{{$user->id}}" >{{ $user->firstname}}	 {{ $user->lastname}}</a>
						</td>
						<td>{{ $user->email}}</td>
						<td class="text-center">
							{!! $user->approval == 1  ? '<span class="label label-sm label-success">approved</span>' : '<span class="label label-sm label-warning">pending</span>' !!}
						</td>

						<td class="text-right">
							<div class="hidden-sm hidden-xs action-buttons">
								<a class="blue" href="/users/{{$user->id}}">
									<i class="ace-icon fa fa-search-plus bigger-130"></i>
								</a>

								<a class="green" href="/users/{{$user->id}}/edit" >
									<i class="ace-icon fa fa-pencil bigger-130"></i>
								</a>
								
								<!-- delete the users (uses the destroy method DESTROY /users/{id} -->
								<!-- we will add this later since its a little more complicated than the first two buttons -->
								{{ Form::open(array('url' => 'users/' . $user->id, 'style' => 'display: inline-block')) }}
									{{ Form::hidden('_method', 'DELETE') }}
									<a class="red" href="#" onclick="$(this).closest('form').submit(); return false;"><i class="ace-icon fa fa-trash-o bigger-130"></i></a>
								{{ Form::close() }}
				
								<a class="red" href="#">
									
								</a>
							</div>

							<div class="hidden-md hidden-lg">
								<div class="inline pos-rel">
									<button class="btn btn-minier btn-yellow dropdown-toggle" data-toggle="dropdown" data-position="auto">
										<i class="ace-icon fa fa-caret-down icon-only bigger-120"></i>
									</button>

									<ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
										<li>
											<a href="#" class="tooltip-info" data-rel="tooltip" title="View">
												<span class="blue">
													<i class="ace-icon fa fa-search-plus bigger-120"></i>
												</span>
											</a>
										</li>

										<li>
											<a href="#" class="tooltip-success" data-rel="tooltip" title="Edit">
												<span class="green">
													<i class="ace-icon fa fa-pencil-square-o bigger-120"></i>
												</span>
											</a>
										</li>

										<li>
											<a href="#" class="tooltip-error" data-rel="tooltip" title="Delete">
												<span class="red">
													<i class="ace-icon fa fa-trash-o bigger-120"></i>
												</span>
											</a>
										</li>
									</ul>
								</div>
							</div>
						</td>
					</tr>

				@endforeach
				
		
				</tbody>
			</table>
		</div>
	</div>
</div>


@stop


@section('scripts')


@stop

resources/views/users/profile.blade.php
@extends('layouts.default')
@section('content')


<div class="page-header">
<h1>users</h1>
</div>

{{ Form::model($user, array('route' => array('users.update', $user->id)), 'POST') }}

<input type="hidden" name="_method" value="PUT" />
	<ul>
		<li>
			{{ Form::label('firstname', 'Firstname:') }}
			{{ Form::text('firstname') }}
		</li>
		<li>
			{{ Form::label('lastname', 'Lastname:') }}
			{{ Form::text('lastname') }}
		</li>
		<li>
			{{ Form::label('role_id', 'Role_id:') }}
			{{ Form::text('role_id') }}
		</li>
		<li>
			{{ Form::label('password', 'Password:') }}
			{{ Form::text('password') }}
		</li>
		<li>
			{{ Form::label('email', 'Email:') }}
			{{ Form::text('email') }}
		</li>
		<li>
			{{ Form::label('remember_token', 'Remember_token:') }}
			{{ Form::text('remember_token') }}
		</li>
		<li>
			{{ Form::label('created_at', 'Created_at:') }}
			{{ Form::text('created_at') }}
		</li>
		<li>
			{{ Form::label('updated_at', 'Updated_at:') }}
			{{ Form::text('updated_at') }}
		</li>
		<li>
			{{ Form::submit() }}
		</li>
	</ul>
{{ Form::close() }}

@stop

resources/views/users/show.blade.php
@extends('layouts.default')
@section('content')

<div class="page-header">
	<h1>User Profile
	
	<div class="pull-right">


		@if(Auth::user()->authorizeRoles(['superadmin', 'admin']))
		<a href="/users/{{ Auth::user()->id }}/edit " class="btn btn-xs btn-primary">
		<i class="ace-icon fa fa-pencil-square-o"></i> Edit Profile</a>
		@endif

	</div></h1>
</div>

@if(Session::has('message'))
	<h4 class="text-success">{{ Session::get('message') }}</h4>
@endif

<div class="profile-user-info profile-user-info-striped">
	<div class="profile-info-row">
		<div class="profile-info-name"> First name</div>

		<div class="profile-info-value">
			<span class="editable" id="username">{{ Auth::user()->firstname }}</span>
		</div>
	</div>
	
	<div class="profile-info-row">
		<div class="profile-info-name">Last name</div>

			
		<div class="profile-info-value">
			<span class="editable" id="username">{{ Auth::user()->lastname }}</span>
		</div>
	</div>
	
	<div class="profile-info-row">
		<div class="profile-info-name">Email</div>

			
		<div class="profile-info-value">
			<span class="editable" id="username">{{ Auth::user()->email }}</span>
		</div>
	</div>	

</div>



@stop